import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import { authService } from "@/services/authService";
import { getAllNotices, createNotice, deleteNotice, type Notice } from "@/services/noticeService";
import { getAllInquiries, updateInquiryStatus, type AdmissionInquiry } from "@/services/admissionService";
import { getAllMessages, updateMessageStatus, type ContactMessage } from "@/services/contactService";
import { uploadImage, getAllGalleryImages, deleteImage, type GalleryImage } from "@/services/galleryService";
import { getAllDonations, updateDonationStatus, type Donation } from "@/services/donationService";
import { createResource, deleteResource, getAllResources, updateResource, type SchoolResource } from "@/services/resourceService";
import { createStudent, deleteStudent, getAllStudents, updateStudent, type Student, type StudentInput } from "@/services/studentService";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Bell, Check, ExternalLink, FileText, GraduationCap, Heart, Image as ImageIcon, Inbox, LayoutDashboard, LogOut, Mail, Pencil, Plus, RefreshCw, Search, Trash2, Users } from "lucide-react";

const fmt = (v: string | null) => v ? new Date(v).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }) : "—";
const tone = (s?: string | null) => ["new","pending","urgent"].includes(s || "") ? "bg-amber-100 text-amber-800" : ["received","contacted","replied","admitted","published"].includes(s || "") ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-700";
const emptyStudent: StudentInput = { admission_number:"", first_name:"", last_name:null, date_of_birth:null, gender:null, class_name:"", section:null, academic_year:"2026-27", guardian_name:"", guardian_phone:"", guardian_email:null, address:null, admission_date:new Date().toISOString().slice(0,10), status:"active", fee_status:"pending", notes:null, source_inquiry_id:null };

export default function AdminDashboard() {
  const router = useRouter();
  const [loading, setLoading] = useState(true), [refreshing, setRefreshing] = useState(false), [query, setQuery] = useState("");
  const [notices, setNotices] = useState<Notice[]>([]), [inquiries, setInquiries] = useState<AdmissionInquiry[]>([]), [messages, setMessages] = useState<ContactMessage[]>([]);
  const [images, setImages] = useState<GalleryImage[]>([]), [donations, setDonations] = useState<Donation[]>([]), [resources, setResources] = useState<SchoolResource[]>([]);
  const [students, setStudents] = useState<Student[]>([]), [student, setStudent] = useState<StudentInput>(emptyStudent), [editingStudent, setEditingStudent] = useState<string|null>(null), [studentError, setStudentError] = useState("");
  const [notice, setNotice] = useState({title:"",content:"",priority:"medium"}), [resource, setResource] = useState({title:"",description:"",url:"",category:"general",audience:"all",is_published:true});
  const [noticeFeedback, setNoticeFeedback] = useState<{type:"success"|"error";message:string}|null>(null);
  const [category, setCategory] = useState("events"), [uploading, setUploading] = useState(false);

  async function load(spin=false) { if(spin)setRefreshing(true); const [a,b,c,d,e,f,g]=await Promise.all([getAllNotices(),getAllInquiries(),getAllMessages(),getAllGalleryImages(),getAllDonations(),getAllResources(),getAllStudents()]); setNotices(a);setInquiries(b);setMessages(c);setImages(d);setDonations(e);setResources(f);setStudents(g);setRefreshing(false); }
  useEffect(()=>{(async()=>{if(!await authService.getCurrentUser()) return void router.replace("/admin/login");await load();setLoading(false)})()},[router]);
  const open=inquiries.filter(i=>!["admitted","declined"].includes(i.status||"new")).length, unread=messages.filter(m=>(m.status||"new")==="new").length, pending=donations.filter(d=>(d.status||"pending")==="pending").length;
  const iq=useMemo(()=>inquiries.filter(i=>[i.student_name,i.parent_name,i.phone,i.email,i.class_applying].some(v=>v?.toLowerCase().includes(query.toLowerCase()))),[inquiries,query]);
  const mq=useMemo(()=>messages.filter(m=>[m.name,m.email,m.phone,m.subject].some(v=>v?.toLowerCase().includes(query.toLowerCase()))),[messages,query]);
  async function upload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setUploading(true);if((await uploadImage(f,category)).success)await load();setUploading(false);e.target.value=""}
  async function remove(label:string,action:()=>Promise<unknown>){if(confirm(`Delete this ${label}?`)){await action();await load()}}
  async function saveStudent(e:React.FormEvent){e.preventDefault();setStudentError("");const result=editingStudent?await updateStudent(editingStudent,student):await createStudent(student);if(result.success){setStudent(emptyStudent);setEditingStudent(null);await load()}else setStudentError(result.error||"Unable to save student")}
  async function publishNotice(e:React.FormEvent){e.preventDefault();setNoticeFeedback(null);const result=await createNotice(notice.title,notice.content,notice.priority as "urgent"|"high"|"medium"|"low");if(result.success){setNotice({title:"",content:"",priority:"medium"});setNoticeFeedback({type:"success",message:"Notice published. It is now available on the home page."});window.dispatchEvent(new Event("school-notices-updated"));await load()}else setNoticeFeedback({type:"error",message:result.error||"Notice could not be published."})}
  if(loading)return <div className="min-h-screen grid place-items-center bg-slate-50 text-slate-500">Opening operations portal…</div>;

  const nav = [["overview","Overview",LayoutDashboard],["students","Students",GraduationCap],["admissions","Admissions",Users],["messages","Messages",Inbox],["notices","Notice board",Bell],["resources","Forms & links",FileText],["gallery","Gallery",ImageIcon],["donations","Donations",Heart]] as Array<[string,string,React.ElementType]>;
  return <div className="min-h-screen bg-[linear-gradient(180deg,#f2fbfa_0%,#fffaf0_42%,#ffffff_100%)]"><header className="border-b-4 border-amber-400 bg-[#073b4c] text-white shadow-lg"><div className="container flex flex-wrap items-center justify-between gap-4 py-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Sri Balaji Educational Trust</p><h1 className="mt-1 font-display text-2xl font-bold">School Operations Portal</h1><p className="text-sm text-white/70">Admissions, communication and website content in one place</p></div><div className="flex gap-2"><Button asChild variant="secondary" size="sm"><Link href="/" target="_blank">Website <ExternalLink className="ml-2 h-4 w-4"/></Link></Button><Button variant="outline" size="sm" className="border-white/30 bg-transparent text-white hover:bg-white/10 hover:text-white" onClick={()=>load(true)}><RefreshCw className={`mr-2 h-4 w-4 ${refreshing?"animate-spin":""}`}/>Refresh</Button><Button variant="secondary" size="sm" onClick={async()=>{await authService.signOut();router.push("/admin/login")}}><LogOut className="mr-2 h-4 w-4"/>Sign out</Button></div></div></header>
  <main className="container py-7"><section className="mb-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{([["Active students",students.filter(s=>s.status==="active").length,GraduationCap,"Current student register"],["Open admissions",open,Users,"Needs follow-up"],["New messages",unread,Mail,"From contact form"],["Pending donations",pending,Heart,"Awaiting confirmation"]] as Array<[string,number,React.ElementType,string]>).map(([l,v,I,h])=><Card key={l} className="border-0 p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{l}</p><p className="mt-2 text-3xl font-bold">{v}</p><p className="text-xs text-slate-500">{h}</p></div><span className="h-fit rounded-xl bg-primary/10 p-3 text-primary"><I className="h-5 w-5"/></span></div></Card>)}</section>
  <Tabs defaultValue="overview"><TabsList className="mb-6 h-auto w-full justify-start gap-1 overflow-x-auto rounded-xl bg-white p-2 shadow-sm">{nav.map(([v,l,I])=><TabsTrigger key={v} value={v} className="gap-2 whitespace-nowrap"><I className="h-4 w-4"/>{l}</TabsTrigger>)}</TabsList>
  <TabsContent value="overview" className="grid gap-6 lg:grid-cols-2"><Card className="p-6"><h2 className="text-xl font-bold">Today’s work queue</h2><p className="text-sm text-slate-500">Items that need attention from the school office.</p><div className="mt-5 space-y-3">{([[`${open} admission inquiries`,"Contact parents and update progress",Users],[`${unread} unread messages`,"Reply to visitor questions",Mail],[`${pending} pending donations`,"Verify and mark received",Heart]] as Array<[string,string,React.ElementType]>).map(([t,d,I])=><div key={t} className="flex items-center gap-4 rounded-xl border p-4"><span className="rounded-lg bg-primary/10 p-2 text-primary"><I className="h-5 w-5"/></span><span><b className="block">{t}</b><small className="text-slate-500">{d}</small></span></div>)}</div></Card><Card className="p-6"><h2 className="text-xl font-bold">Website publishing</h2><p className="text-sm text-slate-500">Live content managed by the office.</p><div className="mt-5 space-y-4">{[["Notices",notices.length],["Gallery images",images.length],["Forms and links",resources.filter(r=>r.is_published).length]].map(([l,v])=><div key={String(l)} className="flex justify-between border-b pb-4"><span>{String(l)}</span><b className="text-xl">{String(v)}</b></div>)}</div></Card></TabsContent>
  <TabsContent value="students" className="grid gap-6 xl:grid-cols-[.85fr_1.15fr]">
    <Card className="h-fit p-6"><h2 className="text-xl font-bold">{editingStudent?"Edit student":"Add student"}</h2><p className="text-sm text-slate-500">Maintain the official school student register.</p>{studentError&&<Alert variant="destructive" className="mt-4"><AlertDescription>{studentError}</AlertDescription></Alert>}
      <form onSubmit={saveStudent} className="mt-5 space-y-4">
        <div className="grid grid-cols-2 gap-3"><Field label="Admission number"><Input required value={student.admission_number} onChange={e=>setStudent({...student,admission_number:e.target.value})}/></Field><Field label="Academic year"><Input required value={student.academic_year} onChange={e=>setStudent({...student,academic_year:e.target.value})}/></Field></div>
        <div className="grid grid-cols-2 gap-3"><Field label="First name"><Input required value={student.first_name} onChange={e=>setStudent({...student,first_name:e.target.value})}/></Field><Field label="Last name"><Input value={student.last_name||""} onChange={e=>setStudent({...student,last_name:e.target.value||null})}/></Field></div>
        <div className="grid grid-cols-3 gap-3"><Field label="Class"><Input required value={student.class_name} onChange={e=>setStudent({...student,class_name:e.target.value})}/></Field><Field label="Section"><Input value={student.section||""} onChange={e=>setStudent({...student,section:e.target.value||null})}/></Field><Pick label="Status" value={student.status} values={["active","inactive","graduated","transferred"]} run={v=>setStudent({...student,status:v})}/></div>
        <div className="grid grid-cols-2 gap-3"><Field label="Guardian"><Input required value={student.guardian_name} onChange={e=>setStudent({...student,guardian_name:e.target.value})}/></Field><Field label="Phone"><Input required value={student.guardian_phone} onChange={e=>setStudent({...student,guardian_phone:e.target.value})}/></Field></div>
        <div className="grid grid-cols-2 gap-3"><Field label="Guardian email"><Input type="email" value={student.guardian_email||""} onChange={e=>setStudent({...student,guardian_email:e.target.value||null})}/></Field><Pick label="Fee status" value={student.fee_status} values={["pending","partial","paid","waived"]} run={v=>setStudent({...student,fee_status:v})}/></div>
        <Field label="Address"><Textarea value={student.address||""} onChange={e=>setStudent({...student,address:e.target.value||null})}/></Field>
        <div className="flex gap-2"><Button><Plus className="mr-2 h-4 w-4"/>{editingStudent?"Save student":"Add student"}</Button>{editingStudent&&<Button type="button" variant="outline" onClick={()=>{setEditingStudent(null);setStudent(emptyStudent)}}>Cancel</Button>}</div>
      </form>
    </Card>
    <div className="min-w-0 space-y-4"><SearchBox value={query} set={setQuery} text="Search any student field: name, ID, class, guardian, phone, email, status or fees"/><Card className="overflow-hidden border-primary/20 shadow-md"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-[#073b4c] text-white"><tr>{["Admission ID","Student","Class","Academic year","Guardian","Contact","Status","Fees","Actions"].map(h=><th key={h} className="px-4 py-3 font-semibold">{h}</th>)}</tr></thead><tbody className="divide-y">{students.filter(s=>Object.values(s).some(v=>String(v??"").toLowerCase().includes(query.toLowerCase()))).map(s=><tr key={s.id} className="bg-white transition hover:bg-amber-50"><td className="px-4 py-3 font-bold text-primary">{s.admission_number}</td><td className="px-4 py-3"><b className="block text-foreground">{s.first_name} {s.last_name}</b><span className="text-xs text-muted-foreground">Admitted {fmt(s.admission_date)}</span></td><td className="px-4 py-3">{s.class_name}{s.section?` – ${s.section}`:""}</td><td className="px-4 py-3">{s.academic_year}</td><td className="px-4 py-3">{s.guardian_name}</td><td className="px-4 py-3"><a className="block text-primary" href={`tel:${s.guardian_phone}`}>{s.guardian_phone}</a>{s.guardian_email&&<a className="text-xs text-primary" href={`mailto:${s.guardian_email}`}>{s.guardian_email}</a>}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-xs font-bold capitalize ${tone(s.status)}`}>{s.status}</span></td><td className="px-4 py-3 capitalize">{s.fee_status}</td><td className="px-4 py-3"><div className="flex gap-1"><Button size="sm" variant="outline" aria-label={`Edit ${s.first_name}`} onClick={()=>{setEditingStudent(s.id);setStudent({admission_number:s.admission_number,first_name:s.first_name,last_name:s.last_name,date_of_birth:s.date_of_birth,gender:s.gender,class_name:s.class_name,section:s.section,academic_year:s.academic_year,guardian_name:s.guardian_name,guardian_phone:s.guardian_phone,guardian_email:s.guardian_email,address:s.address,admission_date:s.admission_date,status:s.status,fee_status:s.fee_status,notes:s.notes,source_inquiry_id:s.source_inquiry_id})}}><Pencil className="h-4 w-4"/></Button><Button size="sm" variant="outline" aria-label={`Mark ${s.first_name} fees paid`} onClick={async()=>{await updateStudent(s.id,{fee_status:"paid"});await load()}}><Check className="h-4 w-4"/></Button><Button size="sm" variant="destructive" aria-label={`Delete ${s.first_name}`} onClick={()=>remove("student record",()=>deleteStudent(s.id))}><Trash2 className="h-4 w-4"/></Button></div></td></tr>)}{students.length===0&&<tr><td colSpan={9} className="px-6 py-12 text-center text-muted-foreground">No students yet. Use the form to add the first student.</td></tr>}</tbody></table></div></Card></div>
  </TabsContent>
  <TabsContent value="admissions" className="space-y-4"><SearchBox value={query} set={setQuery} text="Search student, parent, phone or class"/>{iq.length?iq.map(i=><Record key={i.id} title={i.student_name} status={i.status} when={i.created_at}><p><b>Parent:</b> {i.parent_name} · <b>Class:</b> {i.class_applying}</p><p><a href={`tel:${i.phone}`} className="text-primary">{i.phone}</a>{i.email&&<> · <a href={`mailto:${i.email}`} className="text-primary">{i.email}</a></>}</p>{i.message&&<p className="mt-2 rounded-lg bg-slate-50 p-3">{i.message}</p>}<Actions values={["new","contacted","admitted","declined"]} current={i.status} run={async s=>{await updateInquiryStatus(i.id,s);await load()}}/><Button className="mt-2" size="sm" onClick={()=>{setStudent({...emptyStudent,first_name:i.student_name,guardian_name:i.parent_name,guardian_phone:i.phone,guardian_email:i.email,class_name:i.class_applying,source_inquiry_id:i.id});(document.querySelector('[data-state][value="students"]') as HTMLElement)?.click()}}>Enroll as student</Button></Record>):<Empty text="No admission inquiries found."/>}</TabsContent>
  <TabsContent value="messages" className="space-y-4"><SearchBox value={query} set={setQuery} text="Search sender, subject, email or phone"/>{mq.length?mq.map(m=><Record key={m.id} title={m.name} status={m.status} when={m.created_at}><b>{m.subject||"General enquiry"}</b><p><a href={`mailto:${m.email}`} className="text-primary">{m.email}</a>{m.phone&&<> · <a href={`tel:${m.phone}`} className="text-primary">{m.phone}</a></>}</p><p className="mt-2 rounded-lg bg-slate-50 p-3">{m.message}</p><Actions values={["new","read","replied"]} current={m.status} run={async s=>{await updateMessageStatus(m.id,s as "new"|"read"|"replied");await load()}}/></Record>):<Empty text="No contact messages found."/>}</TabsContent>
  <TabsContent value="notices" className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card className="h-fit border-primary/20 p-6 shadow-md"><h2 className="font-display text-xl font-bold text-[#002147]">Publish a notice</h2><p className="text-sm text-muted-foreground">Published notices appear in Latest notices on the home page.</p>{noticeFeedback&&<Alert variant={noticeFeedback.type==="error"?"destructive":"default"} className="mt-4"><AlertDescription>{noticeFeedback.message}</AlertDescription></Alert>}<form className="mt-5 space-y-4" onSubmit={publishNotice}><Field label="Title"><Input required value={notice.title} onChange={e=>setNotice({...notice,title:e.target.value})}/></Field><Field label="Message"><Textarea required rows={5} value={notice.content} onChange={e=>setNotice({...notice,content:e.target.value})}/></Field><Field label="Priority"><Select value={notice.priority} onValueChange={v=>setNotice({...notice,priority:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["urgent","high","medium","low"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field><Button><Plus className="mr-2 h-4 w-4"/>Publish to home page</Button></form></Card><div className="space-y-4">{notices.map(n=><Record key={n.id} title={n.title} status={n.priority} when={n.created_at}><p>{n.content}</p><Button className="mt-4" size="sm" variant="destructive" onClick={()=>remove("notice",()=>deleteNotice(n.id))}><Trash2 className="h-4 w-4"/></Button></Record>)}{notices.length===0&&<Empty text="No notices have been published yet."/>}</div></TabsContent>
  <TabsContent value="resources" className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card className="h-fit p-6"><h2 className="text-xl font-bold">Add a form or link</h2><p className="text-sm text-slate-500">Admissions, fees, certificates and parent resources.</p><form className="mt-5 space-y-4" onSubmit={async e=>{e.preventDefault();if((await createResource(resource)).success){setResource({title:"",description:"",url:"",category:"general",audience:"all",is_published:true});await load()}}}><Field label="Title"><Input required value={resource.title} onChange={e=>setResource({...resource,title:e.target.value})}/></Field><Field label="Web address"><Input required type="url" placeholder="https://…" value={resource.url} onChange={e=>setResource({...resource,url:e.target.value})}/></Field><Field label="Description"><Textarea value={resource.description} onChange={e=>setResource({...resource,description:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><Pick label="Category" value={resource.category} values={["general","admission","fees","academic","certificate"]} run={v=>setResource({...resource,category:v})}/><Pick label="Audience" value={resource.audience} values={["all","parents","students","staff"]} run={v=>setResource({...resource,audience:v})}/></div><Button><Plus className="mr-2 h-4 w-4"/>Add resource</Button></form></Card><div className="space-y-4">{resources.length?resources.map(r=><Record key={r.id} title={r.title} status={r.is_published?"published":"draft"} when={r.created_at}><p>{r.description||"No description"}</p><p className="text-xs uppercase text-slate-500">{r.category} · {r.audience}</p><a className="inline-flex items-center text-primary" href={r.url} target="_blank" rel="noreferrer">Open link <ExternalLink className="ml-1 h-3 w-3"/></a><div className="mt-4 flex gap-2"><Button size="sm" variant="outline" onClick={async()=>{await updateResource(r.id,{is_published:!r.is_published});await load()}}>{r.is_published?"Unpublish":"Publish"}</Button><Button size="sm" variant="destructive" onClick={()=>remove("resource",()=>deleteResource(r.id))}><Trash2 className="h-4 w-4"/></Button></div></Record>):<Empty text="No forms or links yet."/>}</div></TabsContent>
  <TabsContent value="gallery" className="space-y-6"><Card className="p-6"><h2 className="text-xl font-bold">Add gallery image</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Pick label="Category" value={category} values={["events","classroom","activities","achievements"]} run={setCategory}/><Field label="High-resolution image"><Input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} disabled={uploading}/></Field></div>{uploading&&<p className="mt-2 text-sm">Uploading…</p>}</Card><div className="grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-4">{images.map(i=><Card key={i.id} className="overflow-hidden"><img src={i.image_url} alt={i.description||i.title||"School gallery"} className="aspect-square w-full object-cover"/><div className="flex justify-between p-3"><small>{i.category}</small><Button size="sm" variant="destructive" onClick={()=>remove("image",()=>deleteImage(i.id,i.image_url))}><Trash2 className="h-4 w-4"/></Button></div></Card>)}</div></TabsContent>
  <TabsContent value="donations" className="space-y-4">{donations.length?donations.map(d=><Record key={d.id} title={d.donor_name} status={d.status} when={d.created_at}><p><a href={`tel:${d.phone}`} className="text-primary">{d.phone}</a>{d.email&&<> · <a href={`mailto:${d.email}`} className="text-primary">{d.email}</a></>}</p><p><b>{d.purpose}</b>{d.amount?` · ₹${d.amount.toLocaleString("en-IN")}`:""}</p><Button className="mt-4" size="sm" variant="outline" onClick={async()=>{await updateDonationStatus(d.id,"received");await load()}}><Check className="mr-1 h-4 w-4"/>Mark received</Button></Record>):<Empty text="No donation records yet."/>}</TabsContent>
  </Tabs></main></div>;
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function Pick({label,value,values,run}:{label:string;value:string;values:string[];run:(v:string)=>void}){return <Field label={label}><Select value={value} onValueChange={run}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field>}
function SearchBox({value,set,text}:{value:string;set:(v:string)=>void;text:string}){return <div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input className="bg-white pl-10" value={value} onChange={e=>set(e.target.value)} placeholder={text}/></div>}
function Record({title,status,when,children}:{title:string;status?:string|null;when:string|null;children:React.ReactNode}){return <Card className="p-5 shadow-sm"><div className="mb-4 flex justify-between gap-3"><div><h3 className="text-lg font-bold">{title}</h3><small className="text-slate-500">{fmt(when)}</small></div><span className={`h-fit rounded-full px-2.5 py-1 text-xs font-bold capitalize ${tone(status)}`}>{status||"new"}</span></div><div className="text-sm leading-6 text-slate-600">{children}</div></Card>}
function Actions({values,current,run}:{values:string[];current?:string|null;run:(v:string)=>void}){return <div className="mt-4 flex flex-wrap gap-2">{values.map(v=><Button key={v} size="sm" variant={current===v?"default":"outline"} onClick={()=>run(v)}>{v}</Button>)}</div>}
function Empty({text}:{text:string}){return <Alert><AlertDescription>{text}</AlertDescription></Alert>}

