import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/router";
import Link from "next/link";
import { authService } from "@/services/authService";
import { getAllNotices, createNotice, deleteNotice, type Notice } from "@/services/noticeService";
import { getAllInquiries, updateInquiryStatus, type AdmissionInquiry } from "@/services/admissionService";
import { getAllMessages, updateMessageStatus, type ContactMessage } from "@/services/contactService";
import { uploadImage, getAllGalleryImages, deleteImage, type GalleryImage } from "@/services/galleryService";
import { getAllDonations, updateDonationStatus, type Donation } from "@/services/donationService";
import { createResource, deleteResource, getAllResources, updateResource, type SchoolResource } from "@/services/resourceService";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Card } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { BarChart3, Bell, Check, ExternalLink, FileText, Heart, Image as ImageIcon, Inbox, LayoutDashboard, LogOut, Mail, Plus, RefreshCw, Search, Trash2, Users } from "lucide-react";

const fmt = (v: string | null) => v ? new Date(v).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" }) : "—";
const tone = (s?: string | null) => ["new","pending","urgent"].includes(s || "") ? "bg-amber-100 text-amber-800" : ["received","contacted","replied","admitted","published"].includes(s || "") ? "bg-emerald-100 text-emerald-800" : "bg-slate-100 text-slate-700";

export default function AdminDashboard() {
  const router = useRouter();
  const [loading, setLoading] = useState(true), [refreshing, setRefreshing] = useState(false), [query, setQuery] = useState("");
  const [notices, setNotices] = useState<Notice[]>([]), [inquiries, setInquiries] = useState<AdmissionInquiry[]>([]), [messages, setMessages] = useState<ContactMessage[]>([]);
  const [images, setImages] = useState<GalleryImage[]>([]), [donations, setDonations] = useState<Donation[]>([]), [resources, setResources] = useState<SchoolResource[]>([]);
  const [notice, setNotice] = useState({title:"",content:"",priority:"medium"}), [resource, setResource] = useState({title:"",description:"",url:"",category:"general",audience:"all",is_published:true});
  const [category, setCategory] = useState("events"), [uploading, setUploading] = useState(false);

  async function load(spin=false) { if(spin)setRefreshing(true); const [a,b,c,d,e,f]=await Promise.all([getAllNotices(),getAllInquiries(),getAllMessages(),getAllGalleryImages(),getAllDonations(),getAllResources()]); setNotices(a);setInquiries(b);setMessages(c);setImages(d);setDonations(e);setResources(f);setRefreshing(false); }
  useEffect(()=>{(async()=>{if(!await authService.getCurrentUser()) return void router.replace("/admin/login");await load();setLoading(false)})()},[router]);
  const open=inquiries.filter(i=>!["admitted","declined"].includes(i.status||"new")).length, unread=messages.filter(m=>(m.status||"new")==="new").length, pending=donations.filter(d=>(d.status||"pending")==="pending").length;
  const iq=useMemo(()=>inquiries.filter(i=>[i.student_name,i.parent_name,i.phone,i.email,i.class_applying].some(v=>v?.toLowerCase().includes(query.toLowerCase()))),[inquiries,query]);
  const mq=useMemo(()=>messages.filter(m=>[m.name,m.email,m.phone,m.subject].some(v=>v?.toLowerCase().includes(query.toLowerCase()))),[messages,query]);
  async function upload(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setUploading(true);if((await uploadImage(f,category)).success)await load();setUploading(false);e.target.value=""}
  async function remove(label:string,action:()=>Promise<unknown>){if(confirm(`Delete this ${label}?`)){await action();await load()}}
  if(loading)return <div className="min-h-screen grid place-items-center bg-slate-50 text-slate-500">Opening operations portal…</div>;

  const nav = [["overview","Overview",LayoutDashboard],["admissions","Admissions",Users],["messages","Messages",Inbox],["notices","Notice board",Bell],["resources","Forms & links",FileText],["gallery","Gallery",ImageIcon],["donations","Donations",Heart]] as Array<[string,string,React.ElementType]>;
  return <div className="min-h-screen bg-slate-50"><header className="border-b bg-[#073b4c] text-white"><div className="container flex flex-wrap items-center justify-between gap-4 py-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Sri Balaji Education</p><h1 className="mt-1 text-2xl font-bold">School Operations Portal</h1><p className="text-sm text-white/70">Admissions, communication and website content in one place</p></div><div className="flex gap-2"><Button asChild variant="secondary" size="sm"><Link href="/" target="_blank">Website <ExternalLink className="ml-2 h-4 w-4"/></Link></Button><Button variant="outline" size="sm" className="border-white/30 bg-transparent text-white hover:bg-white/10 hover:text-white" onClick={()=>load(true)}><RefreshCw className={`mr-2 h-4 w-4 ${refreshing?"animate-spin":""}`}/>Refresh</Button><Button variant="secondary" size="sm" onClick={async()=>{await authService.signOut();router.push("/admin/login")}}><LogOut className="mr-2 h-4 w-4"/>Sign out</Button></div></div></header>
  <main className="container py-7"><section className="mb-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{([["Open admissions",open,Users,"Needs follow-up"],["New messages",unread,Mail,"From contact form"],["Pending donations",pending,Heart,"Awaiting confirmation"],["Published content",notices.length+images.length+resources.filter(r=>r.is_published).length,BarChart3,"Notices, images & links"]] as Array<[string,number,React.ElementType,string]>).map(([l,v,I,h])=><Card key={l} className="border-0 p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-sm text-slate-500">{l}</p><p className="mt-2 text-3xl font-bold">{v}</p><p className="text-xs text-slate-500">{h}</p></div><span className="h-fit rounded-xl bg-primary/10 p-3 text-primary"><I className="h-5 w-5"/></span></div></Card>)}</section>
  <Tabs defaultValue="overview"><TabsList className="mb-6 h-auto w-full justify-start gap-1 overflow-x-auto rounded-xl bg-white p-2 shadow-sm">{nav.map(([v,l,I])=><TabsTrigger key={v} value={v} className="gap-2 whitespace-nowrap"><I className="h-4 w-4"/>{l}</TabsTrigger>)}</TabsList>
  <TabsContent value="overview" className="grid gap-6 lg:grid-cols-2"><Card className="p-6"><h2 className="text-xl font-bold">Today’s work queue</h2><p className="text-sm text-slate-500">Items that need attention from the school office.</p><div className="mt-5 space-y-3">{([[`${open} admission inquiries`,"Contact parents and update progress",Users],[`${unread} unread messages`,"Reply to visitor questions",Mail],[`${pending} pending donations`,"Verify and mark received",Heart]] as Array<[string,string,React.ElementType]>).map(([t,d,I])=><div key={t} className="flex items-center gap-4 rounded-xl border p-4"><span className="rounded-lg bg-primary/10 p-2 text-primary"><I className="h-5 w-5"/></span><span><b className="block">{t}</b><small className="text-slate-500">{d}</small></span></div>)}</div></Card><Card className="p-6"><h2 className="text-xl font-bold">Website publishing</h2><p className="text-sm text-slate-500">Live content managed by the office.</p><div className="mt-5 space-y-4">{[["Notices",notices.length],["Gallery images",images.length],["Forms and links",resources.filter(r=>r.is_published).length]].map(([l,v])=><div key={String(l)} className="flex justify-between border-b pb-4"><span>{String(l)}</span><b className="text-xl">{String(v)}</b></div>)}</div></Card></TabsContent>
  <TabsContent value="admissions" className="space-y-4"><SearchBox value={query} set={setQuery} text="Search student, parent, phone or class"/>{iq.length?iq.map(i=><Record key={i.id} title={i.student_name} status={i.status} when={i.created_at}><p><b>Parent:</b> {i.parent_name} · <b>Class:</b> {i.class_applying}</p><p><a href={`tel:${i.phone}`} className="text-primary">{i.phone}</a>{i.email&&<> · <a href={`mailto:${i.email}`} className="text-primary">{i.email}</a></>}</p>{i.message&&<p className="mt-2 rounded-lg bg-slate-50 p-3">{i.message}</p>}<Actions values={["new","contacted","admitted","declined"]} current={i.status} run={async s=>{await updateInquiryStatus(i.id,s);await load()}}/></Record>):<Empty text="No admission inquiries found."/>}</TabsContent>
  <TabsContent value="messages" className="space-y-4"><SearchBox value={query} set={setQuery} text="Search sender, subject, email or phone"/>{mq.length?mq.map(m=><Record key={m.id} title={m.name} status={m.status} when={m.created_at}><b>{m.subject||"General enquiry"}</b><p><a href={`mailto:${m.email}`} className="text-primary">{m.email}</a>{m.phone&&<> · <a href={`tel:${m.phone}`} className="text-primary">{m.phone}</a></>}</p><p className="mt-2 rounded-lg bg-slate-50 p-3">{m.message}</p><Actions values={["new","read","replied"]} current={m.status} run={async s=>{await updateMessageStatus(m.id,s as "new"|"read"|"replied");await load()}}/></Record>):<Empty text="No contact messages found."/>}</TabsContent>
  <TabsContent value="notices" className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card className="h-fit p-6"><h2 className="text-xl font-bold">Publish a notice</h2><form className="mt-5 space-y-4" onSubmit={async e=>{e.preventDefault();if((await createNotice(notice.title,notice.content,notice.priority as "urgent"|"high"|"medium"|"low")).success){setNotice({title:"",content:"",priority:"medium"});await load()}}}><Field label="Title"><Input required value={notice.title} onChange={e=>setNotice({...notice,title:e.target.value})}/></Field><Field label="Message"><Textarea required rows={5} value={notice.content} onChange={e=>setNotice({...notice,content:e.target.value})}/></Field><Field label="Priority"><Select value={notice.priority} onValueChange={v=>setNotice({...notice,priority:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["urgent","high","medium","low"].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field><Button><Plus className="mr-2 h-4 w-4"/>Publish</Button></form></Card><div className="space-y-4">{notices.map(n=><Record key={n.id} title={n.title} status={n.priority} when={n.created_at}><p>{n.content}</p><Button className="mt-4" size="sm" variant="destructive" onClick={()=>remove("notice",()=>deleteNotice(n.id))}><Trash2 className="h-4 w-4"/></Button></Record>)}</div></TabsContent>
  <TabsContent value="resources" className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><Card className="h-fit p-6"><h2 className="text-xl font-bold">Add a form or link</h2><p className="text-sm text-slate-500">Admissions, fees, certificates and parent resources.</p><form className="mt-5 space-y-4" onSubmit={async e=>{e.preventDefault();if((await createResource(resource)).success){setResource({title:"",description:"",url:"",category:"general",audience:"all",is_published:true});await load()}}}><Field label="Title"><Input required value={resource.title} onChange={e=>setResource({...resource,title:e.target.value})}/></Field><Field label="Web address"><Input required type="url" placeholder="https://…" value={resource.url} onChange={e=>setResource({...resource,url:e.target.value})}/></Field><Field label="Description"><Textarea value={resource.description} onChange={e=>setResource({...resource,description:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><Pick label="Category" value={resource.category} values={["general","admission","fees","academic","certificate"]} run={v=>setResource({...resource,category:v})}/><Pick label="Audience" value={resource.audience} values={["all","parents","students","staff"]} run={v=>setResource({...resource,audience:v})}/></div><Button><Plus className="mr-2 h-4 w-4"/>Add resource</Button></form></Card><div className="space-y-4">{resources.length?resources.map(r=><Record key={r.id} title={r.title} status={r.is_published?"published":"draft"} when={r.created_at}><p>{r.description||"No description"}</p><p className="text-xs uppercase text-slate-500">{r.category} · {r.audience}</p><a className="inline-flex items-center text-primary" href={r.url} target="_blank" rel="noreferrer">Open link <ExternalLink className="ml-1 h-3 w-3"/></a><div className="mt-4 flex gap-2"><Button size="sm" variant="outline" onClick={async()=>{await updateResource(r.id,{is_published:!r.is_published});await load()}}>{r.is_published?"Unpublish":"Publish"}</Button><Button size="sm" variant="destructive" onClick={()=>remove("resource",()=>deleteResource(r.id))}><Trash2 className="h-4 w-4"/></Button></div></Record>):<Empty text="No forms or links yet."/>}</div></TabsContent>
  <TabsContent value="gallery" className="space-y-6"><Card className="p-6"><h2 className="text-xl font-bold">Add gallery image</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><Pick label="Category" value={category} values={["events","classroom","activities","achievements"]} run={setCategory}/><Field label="High-resolution image"><Input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} disabled={uploading}/></Field></div>{uploading&&<p className="mt-2 text-sm">Uploading…</p>}</Card><div className="grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-4">{images.map(i=><Card key={i.id} className="overflow-hidden"><img src={i.image_url} alt={i.description||i.title||"School gallery"} className="aspect-square w-full object-cover"/><div className="flex justify-between p-3"><small>{i.category}</small><Button size="sm" variant="destructive" onClick={()=>remove("image",()=>deleteImage(i.id,i.image_url))}><Trash2 className="h-4 w-4"/></Button></div></Card>)}</div></TabsContent>
  <TabsContent value="donations" className="space-y-4">{donations.length?donations.map(d=><Record key={d.id} title={d.donor_name} status={d.status} when={d.created_at}><p><a href={`tel:${d.phone}`} className="text-primary">{d.phone}</a>{d.email&&<> · <a href={`mailto:${d.email}`} className="text-primary">{d.email}</a></>}</p><p><b>{d.purpose}</b>{d.amount?` · ₹${d.amount.toLocaleString("en-IN")}`:""}</p><Button className="mt-4" size="sm" variant="outline" onClick={async()=>{await updateDonationStatus(d.id,"received");await load()}}><Check className="mr-1 h-4 w-4"/>Mark received</Button></Record>):<Empty text="No donation records yet."/>}</TabsContent>
  </Tabs></main></div>;
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function Pick({label,value,values,run}:{label:string;value:string;values:string[];run:(v:string)=>void}){return <Field label={label}><Select value={value} onValueChange={run}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></Field>}
function SearchBox({value,set,text}:{value:string;set:(v:string)=>void;text:string}){return <div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input className="bg-white pl-10" value={value} onChange={e=>set(e.target.value)} placeholder={text}/></div>}
function Record({title,status,when,children}:{title:string;status?:string|null;when:string|null;children:React.ReactNode}){return <Card className="p-5 shadow-sm"><div className="mb-4 flex justify-between gap-3"><div><h3 className="text-lg font-bold">{title}</h3><small className="text-slate-500">{fmt(when)}</small></div><span className={`h-fit rounded-full px-2.5 py-1 text-xs font-bold capitalize ${tone(status)}`}>{status||"new"}</span></div><div className="text-sm leading-6 text-slate-600">{children}</div></Card>}
function Actions({values,current,run}:{values:string[];current?:string|null;run:(v:string)=>void}){return <div className="mt-4 flex flex-wrap gap-2">{values.map(v=><Button key={v} size="sm" variant={current===v?"default":"outline"} onClick={()=>run(v)}>{v}</Button>)}</div>}
function Empty({text}:{text:string}){return <Alert><AlertDescription>{text}</AlertDescription></Alert>}

